# Generated by Django 3.0.8 on 2020-07-31 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Died')),
                ('foto', models.ImageField(upload_to='FOTO_AUTHOR', verbose_name='foto')),
                ('Biografia', models.TextField(help_text='ingrese un breve resumen de la Bibliografiaexit', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Filebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portada', models.ImageField(upload_to='PORTADA_LIBRO', verbose_name='portadas')),
                ('myfile', models.FileField(upload_to='LIBROS', verbose_name='Libro')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='ingres el gènero(ejp:ciencia,poecia)', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subgenero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='especifique el area en la que se enfoca(ejp:programacion,matematicas)', max_length=50)),
                ('genero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestorBiblioteca.Genero')),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(help_text='ingres el tema que trata (ejp:pogramacion enjava, calculo)', max_length=50)),
                ('subgenero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestorBiblioteca.Subgenero')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('Summary', models.TextField(help_text='ingrese un breve resumen dellibro', max_length=500)),
                ('create', models.DateField(auto_now=True)),
                ('update', models.DateField(auto_now_add=True)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestorBiblioteca.Tema')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestorBiblioteca.Author')),
                ('bookfile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestorBiblioteca.Filebook')),
            ],
        ),
    ]
