# Generated by Django 3.0.8 on 2020-08-19 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestorBiblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GestorBiblioteca.Tema'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GestorBiblioteca.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookfile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GestorBiblioteca.Filebook'),
        ),
    ]
